version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        level: DEBUG
        formatter: simple
        class: logging.StreamHandler

    file:
        level: DEBUG
        when: midnight
        backupCount: 5
        formatter: simple
        filename : Thrift.log
        class: logging.handlers.TimedRotatingFileHandler

loggers:
    qsoWidget:
        level: INFO
        propagate: yes
        handlers: [console,file]

    __main__:
        level: DEBUG
        propagate: yes
        handlers: [console]
